import logging
import random

from lib.common import node_antenna_height
from lib.discrete_event_sim_components import Counter
from lib.phy import airtime, estimate_path_loss
from lib.terrain import terrain_obstruction_loss

NODENUM_BROADCAST = 0xFFFFFFFF

logger = logging.getLogger(__name__)

class MeshPacket:
    unique_packet_counter = Counter()
    asym_rng = random.Random(44) # same default seed as in lib/config.py

    @staticmethod
    def seed_asym_rng(seed):
        MeshPacket.asym_rng.seed(seed)

    @staticmethod
    def reset_packet_counter():
        MeshPacket.unique_packet_counter = Counter()

    def __init__(self, conf, nodes, origTxNodeId, destId, txNodeId, plen, seq, genTime, wantAck, isAck, requestId, now, connectivity_map, baseline_pathloss_matrix):
        """Create a new packet and calculate which nodes sense and receive it

        Arguments:
        conf -- simulation Config
        nodes -- set of all nodes in the simulation. For calculating which nodes receive the packet
        origTxNodeId -- ID of originating node
        destId -- ID of destination node (specific node or broadcast)
        txNodeId -- ID of currently transmitting node
        plen -- packet length
        seq -- message sequence number
        genTime -- sim time of original packet generation (different from acks/rebroadcasts)
        wantAck -- this packet wants an ACK
        isAck -- this packet is an ACK packet
        requestId -- ID of packet requesting ACK (only valid for ACK packets)
        now -- current sim time when called, always `env.now`
        connectivity_map -- map of nodeid -> set of reachable nodeids
        baseline_pathloss_matrix -- pre-computed matrix of pathloss between nodes
        """
        self.unique_packet_seq = MeshPacket.unique_packet_counter.get()
        self.conf = conf
        self.origTxNodeId = origTxNodeId
        self.destId = destId
        self.txNodeId = txNodeId
        self.wantAck = wantAck
        self.isAck = isAck
        self.seq = seq
        self.requestId = requestId
        self.genTime = genTime
        self.now = now
        self.txpow = self.conf.PTX
        self.LplAtN = [0 for _ in range(self.conf.NR_NODES)]
        self.rssiAtN = [0 for _ in range(self.conf.NR_NODES)]
        self.sensedByN = [False for _ in range(self.conf.NR_NODES)] # nodes which may possibly sense this packet
        self.detectedByN = [False for _ in range(self.conf.NR_NODES)]
        self.collidedAtN = [False for _ in range(self.conf.NR_NODES)]
        self.receivedAtN = [False for _ in range(self.conf.NR_NODES)]
        self.onAirToN = [True for _ in range(self.conf.NR_NODES)]

        # configuration values
        self.sf = self.conf.current_preset["sf"]
        self.cr = self.conf.current_preset["cr"]
        self.bw = self.conf.current_preset["bw"]
        self.freq = self.conf.FREQ
        self.tx_node = next(n for n in nodes if n.nodeid == self.txNodeId)

        logger.debug(f"{self.now:.3f} Packet {self.unique_packet_seq} for msg {self.seq} generated by node {self.txNodeId}")

        # calculate reception at all other nodes
        for rx_node in nodes:
            if rx_node.nodeid == self.txNodeId:
                continue

            # reduce calculations just to plausibly reachable nodes. This is initialized
            # before sim start, and updated whenever a moving node's position is updated,
            # so is always an accurate map of what nodes could (with extra margin) even
            # sense each other.
            if self.conf.ENABLE_CONNECTIVITY_MAP and not connectivity_map[self.txNodeId].__contains__(rx_node.nodeid):
                logger.debug(f"{self.now:.3f} skipping {self.txNodeId} -> {rx_node.nodeid} computation. connectivity map: {connectivity_map[self.txNodeId]}")
                if conf.MODEL_ASYMMETRIC_LINKS:
                    # Each tx -> rx computation we skip gets the asrm_rng one call out
                    # of sync between simulations with and without the connectivity
                    # map optimization. Thus particular tx -> rx calculations
                    # change between the optimization, which can lead to changes
                    # in sim behavior between the optimization being on/off, leading
                    # to inconsistencies beteen the optimization being on/off.
                    #
                    # Keep things balanced by 'unnecessarily' calling the rng here.
                    MeshPacket.asym_rng.gauss(0, conf.MODEL_ASYMMETRIC_LINKS_STDDEV)
                continue

            if self.conf.ENABLE_CONNECTIVITY_MAP:
                # look up baseline path loss from matrix, since we've already computed it.
                baseline_pathloss = baseline_pathloss_matrix[self.txNodeId][rx_node.nodeid]
            else:
                dist_3d = self.tx_node.position.euclidean_distance(rx_node.position)
                baseline_pathloss = estimate_path_loss(
                    self.conf,
                    dist_3d,
                    self.freq,
                    node_antenna_height(self.tx_node),
                    node_antenna_height(rx_node),
                )
                baseline_pathloss += terrain_obstruction_loss(
                    self.conf,
                    self.tx_node.position,
                    rx_node.position,
                    self.freq,
                )

            if conf.MODEL_ASYMMETRIC_LINKS:
                offset = MeshPacket.asym_rng.gauss(0, conf.MODEL_ASYMMETRIC_LINKS_STDDEV)
                logger.debug(f"{self.now:.3f} packet {self.unique_packet_seq} for msg {self.seq} has asym offset {offset} dB")
                if abs(offset) > conf.CONNECTIVITY_MAP_RSSI_MARGIN:
                    logger.warning(f"{self.now:.3f} packet {self.unique_packet_counter} has asymmetric RSSI offset {offset} which is outside margin. This will lead to inconsistent results with the connectivity map optimization.")
            else:
                offset = 0
            self.LplAtN[rx_node.nodeid] = baseline_pathloss + offset
            self.rssiAtN[rx_node.nodeid] = self.txpow + self.tx_node.antennaGain + rx_node.antennaGain - self.LplAtN[rx_node.nodeid]
            if self.rssiAtN[rx_node.nodeid] >= self.conf.current_preset["sensitivity"]:
                self.sensedByN[rx_node.nodeid] = True
            if self.rssiAtN[rx_node.nodeid] >= self.conf.current_preset["cad_threshold"]:
                self.detectedByN[rx_node.nodeid] = True

        self.packetLen = plen
        self.timeOnAir = airtime(self.conf, self.sf, self.cr, self.packetLen, self.bw)
        self.startTime = 0
        self.endTime = 0

        # Routing
        self.retransmissions = self.conf.maxRetransmission
        self.ackReceived = False
        self.hopLimit = self.tx_node.hopLimit


class MeshMessage:
    def __init__(self, origTxNodeId, destId, genTime, seq):
        self.origTxNodeId = origTxNodeId
        self.destId = destId
        self.genTime = genTime
        self.seq = seq
        self.endTime = 0
